import { z } from "zod";

export const FeedConfigSchema = z.object({
  id: z.string(),
  name: z.string(),
  url: z.string().url(),
  type: z.enum(["blog", "updates", "news"]),
  category: z.enum(["Tech", "News", "Blogs"]),
  selectors: z.object({
    container: z.string().optional(),
    title: z.string(),
    link: z.string(),
    date: z.string().optional(),
    content: z.string().optional(),
  }),
  isXml: z.boolean().optional(),
});

export type FeedConfig = z.infer<typeof FeedConfigSchema>;

export const FEEDS: FeedConfig[] = [
  {
    id: "react",
    name: "React",
    url: "https://react.dev/blog",
    type: "blog",
    category: "Tech",
    selectors: {
      container: "article",
      title: "h2, h1",
      link: "a",
      date: "time",
      content: "p",
    },
  },
  {
    id: "react-native",
    name: "React Native",
    url: "https://reactnative.dev/blog",
    type: "blog",
    category: "Tech",
    selectors: {
      container: "article",
      title: "h2, h1",
      link: "a",
      date: "time",
      content: "p",
    },
  },
  {
    id: "cursor",
    name: "Cursor",
    url: "https://cursor.com/blog",
    type: "blog",
    category: "Tech",
    selectors: {
      container: "article",
      title: "h2, h1",
      link: "a",
      date: "time",
      content: "p",
    },
  },
  {
    id: "bun",
    name: "Bun",
    url: "https://bun.com/rss.xml",
    type: "blog",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "biome",
    name: "Biome",
    url: "https://biomejs.dev/blog/rss.xml",
    type: "blog",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "expo",
    name: "Expo",
    url: "https://expo.dev/blog/rss.xml",
    type: "blog",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "hacking-with-swift",
    name: "Hacking with Swift",
    url: "https://www.hackingwithswift.com/articles/rss",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },

  {
    id: "react-status",
    name: "React Status",
    url: "https://react.statuscode.com/rss/",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "this-week-in-react",
    name: "This Week In React",
    url: "https://thisweekinreact.com/articles/rss.xml",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "frontend-focus",
    name: "Frontend Focus",
    url: "https://frontendfoc.us/rss/",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "mobile-dev-weekly",
    name: "Mobile Dev Weekly",
    url: "https://mobiledevweekly.com/rss/",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "node-weekly",
    name: "Node Weekly",
    url: "https://nodeweekly.com/rss/",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "javascript-weekly",
    name: "JavaScript Weekly",
    url: "https://javascriptweekly.com/rss/",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "deno-news",
    name: "Deno News",
    url: "https://deno.com/feed",
    type: "news",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "devopsish",
    name: "DevOps'ish",
    url: "https://devopsish.com/index.xml",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "increment",
    name: "Increment",
    url: "https://increment.com/feed.xml",
    type: "blog",
    category: "Blogs",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "swift-by-sundell",
    name: "Swift by Sundell",
    url: "https://swiftbysundell.com/rss",
    type: "blog",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "lennys-newsletter",
    name: "Lenny's Newsletter",
    url: "https://www.lennysnewsletter.com/feed",
    type: "blog",
    category: "Blogs",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "stratechery",
    name: "Stratechery",
    url: "https://stratechery.com/rss",
    type: "blog",
    category: "Blogs",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "github-blog",
    name: "GitHub Blog",
    url: "https://github.blog/feed/",
    type: "blog",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "josh-comeau",
    name: "Josh Comeau",
    url: "https://www.joshwcomeau.com/rss.xml", // Assumed based on common pattern if fetch succeeds
    type: "blog",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
  {
    id: "kent-c-dodds",
    name: "Kent C. Dodds (Testing JS)",
    url: "https://kentcdodds.com/blog/rss.xml",
    type: "blog",
    category: "Tech",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },

  {
    id: "hacker-news",
    name: "Hacker News (Frontpage)",
    url: "https://hnrss.org/frontpage",
    type: "news",
    category: "News",
    isXml: true,
    selectors: {
      container: "item",
      title: "title",
      link: "link",
      date: "pubDate",
      content: "description",
    },
  },
];
